version: '3.3'

services:
  web:
    build: ./code
    command: python wsgi.py run -h 0.0.0.0
    volumes:
      - ./code/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
    - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=ask_user
      - POSTGRES_PASSWORD=ask_password
      - POSTGRES_DB=ask_db

volumes:
  postgres_data: