"""empty message

Revision ID: ebc8d9a2fcdc
Revises: 17d1d1123f41
Create Date: 2022-05-16 13:16:23.557016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc8d9a2fcdc'
down_revision = '17d1d1123f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
